version: "3.9"

services:
  db:
    image: postgres:16
    container_name: chat_api_db
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-db:
    image: postgres:16
    container_name: chat_api_test_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_chat
    ports:
      - "5433:5432"

volumes:
  postgres_data:
